# Modul 7a: NumPy für wissenschaftliches Rechnen
## Demonstration und Einführung

---

## 🎯 Einleitung und Lernziele

**Was ist NumPy?**

NumPy (Numerical Python) ist eine der wichtigsten Bibliotheken für wissenschaftliches Rechnen in Python. Sie ermöglicht es, mit **großen Mengen numerischer Daten** effizient zu arbeiten – viel schneller als mit normalen Python-Listen.

**Warum ist NumPy wichtig?**

In der Wissenschaft, Technik und Datenanalyse müssen wir oft:
- Mit vielen Zahlen auf einmal rechnen (z. B. Messwerte von Sensoren)
- Mathematische Operationen durchführen (Matrizenmultiplikation, Statistik)
- Große Datenmengen speichern und verarbeiten

NumPy macht das einfach und schnell!

**Lernziele dieses Moduls:**

1. Verstehen, was ein **Array** ist und wie es sich von Listen unterscheidet
2. Arrays erstellen und manipulieren
3. **Vektorisierte Operationen** nutzen – mehrere Zahlen auf einmal bearbeiten
4. **Broadcasting** verstehen – Arrays unterschiedlicher Größe kombinieren
5. Praktische Anwendungen: Numerische Integration und Bewegungssimulation

---

## 📚 Teil 1: Grundlagen – Arrays statt Listen

### Warum NumPy Arrays besser sind als Listen

**Normale Python-Listen:**

In [ ]:
# Eine Liste mit Zahlen
meine_liste = [1, 2, 3, 4, 5]
meine_liste[0]  # Zugriff auf ein Element: 1

**NumPy Arrays:**

In [ ]:
import numpy as np

# Ein NumPy Array mit den gleichen Zahlen
mein_array = np.array([1, 2, 3, 4, 5])
mein_array[0]  # Zugriff auf ein Element: 1

Das sieht ähnlich aus – aber der Unterschied liegt in der Geschwindigkeit und den Möglichkeiten!

### Demonstration: Listen vs. Arrays

In [ ]:
import numpy as np
import time

# Große Liste
große_liste = list(range(1000000))

# Großes Array
großes_array = np.array(range(1000000))

# Alle Elemente der Liste verdoppeln (langsam)
start = time.time()
ergebnis_liste = [x * 2 for x in große_liste]
zeit_liste = time.time() - start

# Alle Elemente des Arrays verdoppeln (schnell)
start = time.time()
ergebnis_array = großes_array * 2
zeit_array = time.time() - start

print(f"Listen-Methode: {zeit_liste:.4f} Sekunden")
print(f"Array-Methode:  {zeit_array:.4f} Sekunden")
print(f"NumPy ist etwa {zeit_liste / zeit_array:.0f}x schneller!")

**Warum ist NumPy schneller?** NumPy Arrays werden in C (einer schnellen Programmiersprache) verarbeitet, während Python-Listen in reinem Python arbeiten.

---

## 🔨 Teil 2: Arrays erstellen

### Verschiedene Wege, Arrays zu erstellen

In [ ]:
import numpy as np

# 1. Aus einer Liste
array1 = np.array([1, 2, 3, 4, 5])
print("Aus Liste:", array1)

# 2. Mit np.arange() - wie range(), aber für Arrays
array2 = np.arange(0, 10, 2)  # Von 0 bis 10 in 2er-Schritten
print("Mit arange():", array2)

# 3. Mit np.linspace() - gleichmäßig verteilte Punkte
array3 = np.linspace(0, 10, 5)  # 5 Punkte zwischen 0 und 10
print("Mit linspace():", array3)

# 4. Mit np.zeros() - Array voll mit Nullen
array4 = np.zeros(5)
print("Nullen:", array4)

# 5. Mit np.ones() - Array voll mit Einsen
array5 = np.ones(5)
print("Einsen:", array5)

# 6. Mit np.random.random() - Zufallszahlen zwischen 0 und 1
array6 = np.random.random(5)
print("Zufallszahlen:", array6)

### Eigenschaften eines Arrays erforschen

In [ ]:
import numpy as np

# Ein Array erstellen
daten = np.array([1, 2, 3, 4, 5])

# Größe (Länge)
print("Anzahl der Elemente:", len(daten))
print("Form (Shape):", daten.shape)  # (5,) bedeutet ein 1D-Array mit 5 Elementen
print("Datentyp:", daten.dtype)  # int64 oder ähnliches

# Statistische Eigenschaften
print("Summe:", daten.sum())
print("Durchschnitt:", daten.mean())
print("Minimum:", daten.min())
print("Maximum:", daten.max())

**Was ist ein 1D-, 2D- oder 3D-Array?**

In [ ]:
import numpy as np

# 1D-Array: eine Reihe von Zahlen
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Shape:", array_1d.shape)  # (5,)

# 2D-Array: eine Matrix (Tabelle)
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])
print("2D Shape:", array_2d.shape)  # (2, 3) - 2 Reihen, 3 Spalten

# 3D-Array: ein Würfel von Zahlen
array_3d = np.array([[[1, 2], [3, 4]],
                     [[5, 6], [7, 8]]])
print("3D Shape:", array_3d.shape)  # (2, 2, 2)

### 🤔 Verständnisfrage

Wenn du ein Array mit 10 Zufallszahlen erstellst, welche Methode würdest du nutzen: `np.random.random(10)` oder `np.random.random((10,))`? Welcher Unterschied besteht?

---

## ⚡ Teil 3: Vektorisierung – Die Kraft von NumPy

**Vektorisierung** bedeutet: Operationen auf ganze Arrays auf einmal anwenden, statt Element für Element mit Schleifen.

### Beispiel 1: Einfache Rechenoperationen

In [ ]:
import numpy as np

# Array erstellen
zahlen = np.array([1, 2, 3, 4, 5])

# Mit Python-Listen müsste man eine Schleife schreiben:
# ergebnis = []
# for z in zahlen:
#     ergebnis.append(z * 2)

# Mit NumPy: einfach das Array multiplizieren!
verdoppelt = zahlen * 2
print("Original:", zahlen)
print("Verdoppelt:", verdoppelt)

# Das funktioniert mit allen Grundrechenarten
print("Plus 10:", zahlen + 10)
print("Minus 5:", zahlen - 5)
print("Geteilt durch 2:", zahlen / 2)
print("Potenz 2:", zahlen ** 2)

### Beispiel 2: Mathematische Funktionen

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Array von x-Werten
x = np.linspace(0, 2*np.pi, 100)  # 100 Punkte zwischen 0 und 2π

# Die Sinus-Funktion auf alle x-Werte anwenden
y = np.sin(x)

# Plot
plt.figure(figsize=(10, 6))
plt.plot(x, y, 'b-', linewidth=2)
plt.xlabel('x')
plt.ylabel('sin(x)')
plt.title('Sinuskurve mit NumPy')
plt.grid(True)
plt.show()

# Andere mathematische Funktionen
print("Cosinus:", np.cos(x[:5]))  # Die ersten 5 Werte
print("Exponential:", np.exp(x[:3]))  # e^x für die ersten 3 Werte
print("Logarithmus:", np.log([1, 10, 100, 1000]))

### Beispiel 3: Logische Operationen und Filterung

In [ ]:
import numpy as np

# Array mit Messwerten
temperaturen = np.array([18, 22, 25, 30, 28, 15, 19])

# Welche Temperaturen sind über 25°C?
hoch = temperaturen > 25
print("Über 25°C:", hoch)  # [False False True True True False False]

# Die tatsächlichen Werte extrahieren
hohe_temperaturen = temperaturen[temperaturen > 25]
print("Hohe Temperaturen:", hohe_temperaturen)  # [30 28]

# Anzahl der hohen Temperaturen
anzahl = (temperaturen > 25).sum()
print("Anzahl über 25°C:", anzahl)

### 🤔 Verständnisfrage

Wenn du ein Array mit 1000 Zahlen hast und möchtest alle verdoppeln – warum ist `zahlen * 2` besser als eine `for`-Schleife?

---

## 🎲 Teil 4: Broadcasting – Arrays verschiedener Größen kombinieren

**Broadcasting** ist eine magische NumPy-Fähigkeit: Sie können Arrays unterschiedlicher Größe zusammen verwenden!

### Beispiel 1: Zahl mit Array

In [ ]:
import numpy as np

# Array von Messwerten (in Metern)
längen = np.array([1.5, 2.0, 2.5, 3.0])

# Alle in Zentimeter umrechnen: einfach mit 100 multiplizieren
längen_cm = längen * 100
print("Original (m):", längen)
print("Umgerechnet (cm):", längen_cm)

# Das ist Broadcasting! Die Zahl 100 wird "ausgedehnt" auf die Größe des Arrays

### Beispiel 2: Verschiedene Array-Größen

In [ ]:
import numpy as np

# Ein Array mit einer Spalte
spalte = np.array([[1],
                   [2],
                   [3]])
print("Spalte Shape:", spalte.shape)  # (3, 1)

# Ein Array mit einer Reihe
reihe = np.array([10, 20, 30])
print("Reihe Shape:", reihe.shape)  # (3,)

# Addieren! NumPy dehnt beide Arrays automatisch auf (3, 3) aus
ergebnis = spalte + reihe
print("Ergebnis:")
print(ergebnis)
# [[11 21 31]
#  [12 22 32]
#  [13 23 33]]

### Beispiel 3: Praktisches Beispiel – Normalisierung

In [ ]:
import numpy as np

# Messwerte von 3 Sensoren (3 Zeilen, 4 Messungen pro Sensor)
messwerte = np.array([[10, 15, 20, 25],
                      [100, 120, 140, 160],
                      [1000, 1100, 1200, 1300]])

print("Original:")
print(messwerte)

# Durchschnittswerte pro Sensor
durchschnitte = messwerte.mean(axis=1, keepdims=True)
print("\nDurchschnitte pro Sensor:")
print(durchschnitte)

# Alle Werte um den Durchschnitt zentrieren (Normalisierung)
normalisiert = messwerte - durchschnitte
print("\nNormalisiert (um Durchschnitt zentriert):")
print(normalisiert)

### 🤔 Verständnisfrage

Wenn du ein Array der Form (3, 1) und ein Array der Form (3,) addierst, welche Form hat das Ergebnis?

---

## 🔬 Teil 5: Praktische Anwendung – Numerische Integration

**Numerische Integration** bedeutet: Den Flächeninhalt unter einer Kurve berechnen.

### Die Idee

Statt die mathematische Formel zu nutzen, können wir:
1. Die Kurve in kleine Rechtecke aufteilen
2. Die Flächen der Rechtecke addieren
3. Das ist ein sehr guter Näherungswert für das echte Integral

### Beispiel: Fläche unter einer Sinuskurve

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Aufteilen des Intervals [0, π] in n Punkte
n = 50
x = np.linspace(0, np.pi, n)
dx = np.pi / (n - 1)  # Breite eines Rechtecks

# Höhen der Rechtecke (Funktionswerte)
y = np.sin(x)

# Fläche = Summe aller Rechtecke
flaeche = np.sum(y) * dx
print(f"Numerisch berechnete Fläche: {flaeche:.4f}")

# Das echte Ergebnis (mathematisch)
echte_flaeche = 2.0  # ∫₀^π sin(x)dx = 2
print(f"Echte Fläche: {echte_flaeche:.4f}")
print(f"Fehler: {abs(flaeche - echte_flaeche):.4f}")

# Visualisierung
plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
x_fein = np.linspace(0, np.pi, 200)
y_fein = np.sin(x_fein)
plt.plot(x_fein, y_fein, 'b-', linewidth=2, label='sin(x)')
plt.fill_between(x, y, alpha=0.3, label=f'Näherung (n={n})')
plt.bar(x, y, width=dx, alpha=0.3, edgecolor='black')
plt.xlabel('x')
plt.ylabel('sin(x)')
plt.title('Numerische Integration mit Rechtecken')
plt.legend()
plt.grid(True)

# Genauigkeit mit unterschiedlichem n
plt.subplot(1, 2, 2)
n_werte = [10, 20, 50, 100, 200, 500]
fehler = []
for n_test in n_werte:
    x_test = np.linspace(0, np.pi, n_test)
    y_test = np.sin(x_test)
    dx_test = np.pi / (n_test - 1)
    flaeche_test = np.sum(y_test) * dx_test
    fehler.append(abs(flaeche_test - echte_flaeche))

plt.loglog(n_werte, fehler, 'ro-', linewidth=2, markersize=8)
plt.xlabel('Anzahl der Punkte (n)')
plt.ylabel('Fehler')
plt.title('Wie der Fehler mit mehr Punkten abnimmt')
plt.grid(True)
plt.tight_layout()
plt.show()

---

## 🎬 Teil 6: Praktische Anwendung – Bewegungssimulation

Stellen Sie sich vor, wir werfen einen Ball. Mit NumPy können wir seine Position in jedem Moment berechnen.

### Die Physik

- **Geschwindigkeit**: v = Δx / Δt (wie schnell sich etwas bewegt)
- **Beschleunigung**: a = Δv / Δt (wie schnell die Geschwindigkeit sich ändert)
- **Freier Fall**: a = -9.81 m/s² (die Schwerkraft)

### Simulation: Springender Ball

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Parameter
g = 9.81  # Gravitationsbeschleunigung in m/s²
v0 = 20   # Anfangsgeschwindigkeit in m/s (nach oben)
dt = 0.01 # Zeitschritt in Sekunden
t_max = 4 # Gesamtdauer in Sekunden

# Zeitpunkte
t = np.arange(0, t_max, dt)
n = len(t)

# Höhe und Geschwindigkeit initialisieren
y = np.zeros(n)
v = np.zeros(n)

y[0] = 0        # Starten bei Höhe 0
v[0] = v0       # Mit Anfangsgeschwindigkeit

# Simulation: Schritt für Schritt
for i in range(1, n):
    # Neue Geschwindigkeit (Beschleunigung wirkt sich aus)
    v[i] = v[i-1] - g * dt
    
    # Neue Höhe
    y[i] = y[i-1] + v[i] * dt
    
    # Wenn der Ball den Boden berührt, springt er zurück
    if y[i] < 0:
        y[i] = -y[i]           # Höhe spiegeln
        v[i] = -v[i] * 0.9     # Geschwindigkeit umkehren (mit Energieverlust)

# Visualisierung
fig, axes = plt.subplots(2, 2, figsize=(12, 10))

# Höhe über Zeit
axes[0, 0].plot(t, y, 'b-', linewidth=2)
axes[0, 0].axhline(y=0, color='k', linestyle='--', alpha=0.3)
axes[0, 0].set_xlabel('Zeit (s)')
axes[0, 0].set_ylabel('Höhe (m)')
axes[0, 0].set_title('Höhe des Balls über Zeit')
axes[0, 0].grid(True)

# Geschwindigkeit über Zeit
axes[0, 1].plot(t, v, 'r-', linewidth=2)
axes[0, 1].axhline(y=0, color='k', linestyle='--', alpha=0.3)
axes[0, 1].set_xlabel('Zeit (s)')
axes[0, 1].set_ylabel('Geschwindigkeit (m/s)')
axes[0, 1].set_title('Geschwindigkeit des Balls über Zeit')
axes[0, 1].grid(True)

# Phase-Raum: Geschwindigkeit vs. Höhe
axes[1, 0].plot(y, v, 'g-', linewidth=2)
axes[1, 0].scatter(y[0], v[0], color='blue', s=100, label='Start', zorder=5)
axes[1, 0].scatter(y[-1], v[-1], color='red', s=100, label='Ende', zorder=5)
axes[1, 0].set_xlabel('Höhe (m)')
axes[1, 0].set_ylabel('Geschwindigkeit (m/s)')
axes[1, 0].set_title('Phase-Raum')
axes[1, 0].legend()
axes[1, 0].grid(True)

# Animation-ähnliche Darstellung: einige Positionen
indices = np.arange(0, n, int(n/20))  # Jede 20. Position
axes[1, 1].scatter(indices * dt, y[indices], s=50, alpha=0.6)
for idx in indices:
    circle = plt.Circle((indices[0] * dt, y[indices[0]]), 0.5, 
                        fill=False, edgecolor='blue', alpha=0.3)
axes[1, 1].set_xlim(0, t_max)
axes[1, 1].set_ylim(-2, max(y) + 2)
axes[1, 1].set_xlabel('Zeit (s)')
axes[1, 1].set_ylabel('Höhe (m)')
axes[1, 1].set_title('Ball-Positionen zu verschiedenen Zeiten')
axes[1, 1].grid(True)

plt.tight_layout()
plt.show()

print(f"Maximale Höhe: {y.max():.2f} m")
print(f"Erreichte Zeit: {t_max:.2f} s")

### 🤔 Verständnisfrage

In der Simulation: Was würde passieren, wenn wir den Faktor 0.9 bei der Geschwindigkeit entfernen (also `v[i] = -v[i]` statt `v[i] = -v[i] * 0.9`)?

---

## 📊 Teil 7: Zusammenfassung und Wichtige NumPy-Funktionen

| Funktion | Beschreibung | Beispiel |
|----------|-------------|----------|
| `np.array()` | Array aus Liste erstellen | `np.array([1,2,3])` |
| `np.arange()` | Array mit Schritten | `np.arange(0, 10, 2)` |
| `np.linspace()` | Gleichmäßig verteilte Punkte | `np.linspace(0, 10, 5)` |
| `np.zeros()` | Array voll mit Nullen | `np.zeros(5)` |
| `np.ones()` | Array voll mit Einsen | `np.ones(5)` |
| `np.random.random()` | Zufallszahlen | `np.random.random(5)` |
| `.shape` | Größe des Arrays | `arr.shape` |
| `.dtype` | Datentyp | `arr.dtype` |
| `.sum()`, `.mean()`, `.min()`, `.max()` | Statistische Funktionen | `arr.mean()` |
| `np.sin()`, `np.cos()`, `np.exp()`, `np.log()` | Mathematische Funktionen | `np.sin(x)` |

---

## 🔗 Weiterführende Links

- [NumPy Official Documentation](https://numpy.org/doc/stable/)
- [NumPy Beginner's Guide](https://numpy.org/learn/)
- [W3Schools NumPy Tutorial](https://www.w3schools.com/python/numpy/default.asp)
- [Scientific Python Tutorial](https://scipy-lectures.org/)
- [NumPy Broadcasting Explanation](https://numpy.org/doc/stable/user/basics.broadcasting.html)

---

## 📝 Nächste Schritte

Im nächsten Modul werden Sie:
- **p5.js Grundlagen** kennenlernen
- Grafiken und Animationen erstellen
- Ihre NumPy-Kenntnisse mit interaktiven Visualisierungen verbinden

Für jetzt: Probieren Sie die Codebeispiele aus, ändern Sie Parameter und beobachten Sie, was passiert!